# Dependabot configuration
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"

  # Keep MkDocs Python dependencies up to date
  - package-ecosystem: "pip"
    directory: "/Docs"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
