# Deploy MkDocs and push to GitHub Pages
---
name: 📖 Deploy MkDocs to GitHub
# Install, build, and deploy MkDocs to GitHub Pages using content from the Docs folder.

on:
  #pull_request:
  #  branches:
  #    - main
  #  paths:  # Only deploy MkDocs when the contents of the docs folder change or when this workflow changes
  #    - 'Docs/**'
  #    - '.github/workflows/Deploy MkDocs.yml'
  #    - './mkdocs.yml'
  push:
    branches:
      - main  # The branch you want to deploy from
    paths:  # Only deploy MkDocs when the contents of the docs folder change or when this workflow changes
      - 'Docs/**'
      - '.github/workflows/Deploy MkDocs.yml'
      - './mkdocs.yml'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # specify the Python version

      - name: ➕ Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: 👷‍♂️ Build & Deploy MkDocs
        run: |
          mkdocs build
          mkdocs gh-deploy --force
